
name: Upload to S3

on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws_bucket: gitaction-jiangren
          source_dir: .
